Change to postgres package

diff --git a/openmediavault-dcm4chee/usr/share/openmediavault/mkconf/dcm4chee b/openmediavault-dcm4chee/usr/share/openmediavault/mkconf/dcm4chee
--- a/openmediavault-dcm4chee/usr/share/openmediavault/mkconf/dcm4chee
+++ b/openmediavault-dcm4chee/usr/share/openmediavault/mkconf/dcm4chee
@@ -23,35 +23,24 @@ set -e
 SERVICE="dcm4chee"
 SERVICE_XPATH="/config/services/${SERVICE}"
 
-NAME_DCM4CHEE="dcm4chee-mysql_2.18.3.1_amd64.deb"
-NAME_WEASIS="dcm4chee-weasis_3.0.1_all.deb"
+NAME_DCM4CHEE="dcm4chee-psql_2.18.3_amd64.deb"
 LINK_DCM4CHEE="https://github.com/nroduit/openmediavault-dcm4chee/releases/download/v4.0.0/${NAME_DCM4CHEE}"
-LINK_WEASIS="https://github.com/nroduit/openmediavault-dcm4chee/releases/download/v4.0.0/${NAME_WEASIS}"
 PKG_DCM4CHEE="/var/tmp/${NAME_DCM4CHEE}"
-PKG_WEASIS="/var/tmp/${NAME_WEASIS}"
 INSTALL_DIR="/var/lib/${SERVICE}"
 
 stop()
 {
-    if [ -f "/var/run/dcm4chee/dcm4chee.pid" ]; then
-        PID=`cat /var/run/dcm4chee/dcm4chee.pid`;
-        if ! kill -0 $PID > /dev/null 2>&1; then
-            echo "Removing stale pid file"
-            rm /var/run/dcm4chee/dcm4chee.pid
-        else
-            kill -9 $PID;
-        fi
-    fi
+    service dcm4chee stop
 }
 
 start()
 {
-    [ -f "/var/run/dcm4chee/dcm4chee.pid" ] || /etc/init.d/dcm4chee start
+    service dcm4chee start
 }
 
 restart()
 {
-    /etc/init.d/dcm4chee restart
+    service dcm4chee restart
 }
 
 installdependencies()
@@ -62,22 +51,12 @@ installdependencies()
         echo "Downloading dcm4chee package..."
         wget ${LINK_DCM4CHEE} -O ${PKG_DCM4CHEE} || rm -f ${PKG_DCM4CHEE}
     fi
-    
-
-    if [ ! -f "${PKG_WEASIS}" ]; then
-        echo "Downloading weasis package..."
-        wget ${LINK_WEASIS} -O ${PKG_WEASIS} || rm -f ${PKG_WEASIS}
-    fi
 
     echo "Installing dcm4chee..."
-    # Install dcm4chee-mysql and its dependencies
+    # Install dcm4chee-psql and its dependencies
     echo "dpkg -i ${PKG_DCM4CHEE}"
     dpkg -i ${PKG_DCM4CHEE} || apt-get -f install -y
     
-    echo "Installing weasis..."
-    echo "dpkg -i ${PKG_WEASIS}"
-    dpkg -i ${PKG_WEASIS} || apt-get -f install -y
-
     if [ "$(omv_config_get "${SERVICE_XPATH}/enable")" != "0" ]; then
         restart
     fi
@@ -85,8 +64,11 @@ installdependencies()
 
 remove()
 {
-    # Remove dcm4chee-mysql and its dependencies
-    apt-get -f remove dcm4chee-mysql -y || echo "Cannot remove dcm4chee-mysql package correctly!"
+
+    service dcm4chee stop
+
+    # Remove dcm4chee-psql and its dependencies
+    apt-get -f remove dcm4chee-psql -y || echo "Cannot remove dcm4chee-psql package correctly!"
 }
 
 config()
